version: '2'
services:
    webhipster-app:
        image: webhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://webhipster-mysql:3306/webhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    webhipster-mysql:
        extends:
            file: mysql.yml
            service: webhipster-mysql
